# Generated by Django 2.2.15 on 2020-08-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reco_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reco_data',
            new_name='RecoData',
        ),
        migrations.DeleteModel(
            name='MovieReview',
        ),
    ]
