# Generated by Django 2.2.15 on 2020-08-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200822_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rank_id',
            new_name='RankId',
        ),
    ]
